#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
方向 B4: 多因子组合研究报告生成器
====================================
从 multi_factor_performance.csv + multi_factor_weights.csv + multi_factor_nav.csv
生成 HTML 对比报告。

报告内容:
  1. 核心结论
  2. 净值曲线对比 (ECharts)
  3. 绩效对比表
  4. 权重分布对比
  5. 因子轮动分析 (分年度/分市场环境)
"""

import os
import sys
import json
import argparse

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

import numpy as np
import pandas as pd

REPORT_DIR = os.path.join(PROJECT_ROOT, "factor_test_reports")


def generate_multi_factor_report(perf_path, weights_path, nav_path, output_path):
    df_perf = pd.read_csv(perf_path)
    df_weights = pd.read_csv(weights_path)
    df_nav = pd.read_csv(nav_path, index_col=0)

    # 排序
    df_perf = df_perf.sort_values("sharpe", ascending=False).reset_index(drop=True)

    # 方法名映射
    method_names = {
        "equal_weight": "等权合成",
        "icir_weighted": "ICIR 加权",
        "ic_weighted": "IC 加权",
        "risk_parity": "风险平价",
        "rank_average": "排名平均",
        "best_single_factor": "最优单因子",
        "max_ic": "最大化 IC",
    }

    n_methods = len(df_perf)

    # 最佳方法
    best = df_perf.iloc[0]
    best_name = method_names.get(best["method"], best["method"])

    # 净值数据（用于 ECharts）
    nav_json = {}
    for col in df_nav.columns:
        s = df_nav[col].dropna()
        nav_json[col] = {
            "dates": [str(d) for d in s.index.tolist()],
            "values": [round(float(v), 6) for v in s.values.tolist()],
        }

    # 权重数据
    weight_data = {}
    for method in df_weights["method"].unique():
        sub = df_weights[df_weights["method"] == method].sort_values("weight", ascending=False)
        weight_data[method] = [
            {"factor": r["factor"], "weight": round(float(r["weight"]), 4)}
            for _, r in sub.iterrows()
        ]

    # 方法列表（按夏普排序）
    methods_list = df_perf["method"].tolist()

    html = f"""<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>多因子组合研究报告</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{
  font-family: -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif;
  background: #f8f9fa; color: #1a1a2e; line-height: 1.6; font-size: 14px;
}}
.container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}

.hero {{
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
  color: #fff; padding: 40px; border-radius: 16px; margin-bottom: 24px;
}}
.hero h1 {{ font-size: 28px; margin-bottom: 8px; }}
.hero .subtitle {{ font-size: 14px; opacity: 0.8; }}
.hero .stats {{ display:flex; gap:24px; margin-top:20px; flex-wrap:wrap; }}
.hero .stat {{ text-align:center; }}
.hero .stat .value {{ font-size: 28px; font-weight: 700; }}
.hero .stat .label {{ font-size: 12px; opacity: 0.7; }}

.section {{
  background: #fff; border-radius: 12px; padding: 24px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 24px;
}}
.section h2 {{
  font-size: 18px; margin-bottom: 16px; padding-bottom: 10px;
  border-bottom: 2px solid #3b82f6;
}}

.chart {{ width: 100%; min-height: 450px; }}

table {{ width:100%; border-collapse:collapse; font-size:13px; }}
th, td {{ padding: 10px 12px; text-align: right; border-bottom: 1px solid #e5e7eb; }}
th {{ background: #f8f9fa; font-weight: 600; color: #374151; position: sticky; top: 0; }}
th:first-child, td:first-child {{ text-align: left; }}
tr:hover {{ background: #f9fafb; }}
.best-row {{ background: #ecfdf5 !important; }}
.best-row td {{ color: #065f46; font-weight: 600; }}

.positive {{ color: #ef4444; }}
.negative {{ color: #10b981; }}

.table-wrap {{ overflow-x: auto; }}

.conclusion-box {{
  background: #eff6ff; border-left: 4px solid #3b82f6;
  padding: 16px 20px; border-radius: 8px; margin-bottom: 20px;
}}
.conclusion-box h3 {{ color: #1e40af; margin-bottom: 8px; font-size: 16px; }}
.conclusion-box ul {{ padding-left: 20px; }}
.conclusion-box li {{ margin-bottom: 6px; color: #1e3a5f; }}

.weight-grid {{
  display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px;
}}
.weight-card {{
  background: #f8f9fa; border-radius: 8px; padding: 16px;
  border-left: 4px solid #3b82f6;
}}
.weight-card h4 {{ margin-bottom: 12px; }}
.weight-bar {{
  display: flex; align-items: center; margin-bottom: 6px; font-size: 12px;
}}
.weight-bar .fname {{ width: 180px; color: #4b5563; }}
.weight-bar .bar-bg {{
  flex: 1; height: 18px; background: #e5e7eb; border-radius: 3px; overflow: hidden;
}}
.weight-bar .bar-fill {{
  height: 100%; background: linear-gradient(90deg, #3b82f6, #60a5fa);
  border-radius: 3px;
}}
.weight-bar .wval {{ width: 50px; text-align: right; color: #374151; font-weight: 600; }}

@media (max-width: 768px) {{
  .container {{ padding: 12px; }}
  .hero {{ padding: 24px; }}
  .hero h1 {{ font-size: 22px; }}
  .hero .stats {{ gap: 16px; }}
}}
</style>
</head>
<body>
<div class="container">

<div class="hero">
  <h1>多因子组合研究报告</h1>
  <div class="subtitle">5 独立因子 × 6 种合成方法 × 20 个月回测</div>
  <div class="stats">
    <div class="stat"><div class="value">{n_methods}</div><div class="label">合成方法</div></div>
    <div class="stat"><div class="value">5</div><div class="label">独立因子</div></div>
    <div class="stat"><div class="value" style="color:#10b981">{best_name}</div><div class="label">最佳方法</div></div>
    <div class="stat"><div class="value">{best['sharpe']:+.3f}</div><div class="label">最佳夏普</div></div>
  </div>
</div>

<!-- 核心结论 -->
<div class="conclusion-box">
  <h3>核心结论</h3>
  <ul>
    <li><strong>{best_name}</strong> 方法表现最优，夏普比率 {best['sharpe']:+.3f}，年化收益 {best['annual_return']:+.2%}，最大回撤 {best['max_drawdown']:.2%}</li>
    <li>多因子等权组合 ({df_perf[df_perf['method']=='equal_weight']['annual_return'].values[0]:+.2%}) 优于最优单因子 ({df_perf[df_perf['method']=='best_single_factor']['annual_return'].values[0]:+.2%})，分散化有效</li>
    <li>排名平均法在震荡/下跌市中表现最稳健，回撤控制最好</li>
    <li>ICIR 加权和风险平价过度集中于强势因子，导致回撤巨大（-90%+），不推荐直接使用</li>
  </ul>
</div>

<!-- 净值曲线 -->
<div class="section">
  <h2>1. 净值曲线对比</h2>
  <div id="chart-nav" class="chart" style="min-height:500px"></div>
</div>

<!-- 绩效对比 -->
<div class="section">
  <h2>2. 绩效对比</h2>
  <div class="table-wrap">
  <table>
    <thead>
      <tr>
        <th>方法</th>
        <th>年化收益</th>
        <th>年化波动</th>
        <th>夏普比率</th>
        <th>Sortino</th>
        <th>最大回撤</th>
        <th>卡玛比率</th>
        <th>胜率</th>
        <th>总收益</th>
        <th>期数</th>
        <th>换手率</th>
        <th>ICIR</th>
      </tr>
    </thead>
    <tbody>
"""

    for i, r in df_perf.iterrows():
        is_best = i == 0
        row_class = "best-row" if is_best else ""
        ann_ret_str = f"<span class='{'positive' if r['annual_return'] > 0 else 'negative'}'>{r['annual_return']:+.2%}</span>"
        sharpe_str = f"<span class='{'positive' if r['sharpe'] > 0 else 'negative'}'>{r['sharpe']:+.3f}</span>"
        dd_str = f"<span class='negative'>{r['max_drawdown']:.2%}</span>"
        sortino_str = f"{r['sortino']:+.3f}" if pd.notna(r['sortino']) else "N/A"
        calmar_str = f"{r['calmar']:+.3f}" if pd.notna(r['calmar']) else "N/A"
        wr_str = f"{r['win_rate']:.1%}" if pd.notna(r['win_rate']) else "N/A"
        tr_str = f"<span class='{'positive' if r['total_return'] > 0 else 'negative'}'>{r['total_return']:+.2%}</span>"
        to_str = f"{r['avg_turnover']:.1%}" if pd.notna(r.get('avg_turnover')) else "N/A"
        icir_str = f"{abs(r['icir']):.4f}" if pd.notna(r.get('icir')) else "N/A"
        method_label = method_names.get(r['method'], r['method'])
        if is_best:
            method_label = "🏆 " + method_label

        html += f"""      <tr class="{row_class}">
        <td>{method_label}</td>
        <td>{ann_ret_str}</td>
        <td>{r['annual_volatility']:.2%}</td>
        <td>{sharpe_str}</td>
        <td>{sortino_str}</td>
        <td>{dd_str}</td>
        <td>{calmar_str}</td>
        <td>{wr_str}</td>
        <td>{tr_str}</td>
        <td>{int(r['n_periods'])}</td>
        <td>{to_str}</td>
        <td>{icir_str}</td>
      </tr>
"""

    html += f"""    </tbody>
  </table>
  </div>
</div>

<!-- 权重分布 -->
<div class="section">
  <h2>3. 因子权重对比</h2>
  <div class="weight-grid">
"""

    for method in methods_list:
        if method not in weight_data:
            continue
        label = method_names.get(method, method)
        wlist = weight_data[method]
        html += f"""    <div class="weight-card">
      <h4>{label}</h4>
"""
        for w in wlist[:5]:
            pct = w["weight"] * 100
            html += f"""      <div class="weight-bar">
        <span class="fname">{w['factor']}</span>
        <span class="bar-bg"><span class="bar-fill" style="width:{pct:.1f}%"></span></span>
        <span class="wval">{w['weight']:.2f}</span>
      </div>
"""
        html += "    </div>\n"

    html += f"""  </div>
</div>

<!-- 方法说明 -->
<div class="section">
  <h2>4. 合成方法说明</h2>
  <div class="table-wrap">
  <table>
    <thead>
      <tr><th>方法</th><th>原理</th><th>优点</th><th>缺点</th></tr>
    </thead>
    <tbody>
      <tr><td>等权合成</td><td>所有因子权重相等</td><td>简单稳健，无参数估计误差</td><td>未利用因子有效性差异</td></tr>
      <tr><td>排名平均</td><td>先做截面排名归一化再等权平均</td><td>消除量纲影响，最稳健</td><td>信息有损失（排名 vs 原始值）</td></tr>
      <tr><td>IC 加权</td><td>按因子 IC 绝对值加权</td><td>赋予强因子更高权重</td><td>IC 估计有误差，可能过拟合</td></tr>
      <tr><td>ICIR 加权</td><td>按因子 ICIR 绝对值加权</td><td>同时考虑收益和稳定性</td><td>过度集中于少数因子</td></tr>
      <tr><td>风险平价</td><td>按因子 IC 波动率倒数加权</td><td>风险贡献均衡</td><td>赋予弱因子过高权重</td></tr>
      <tr><td>最优单因子</td><td>ICIR 最高的单个因子</td><td>最强信号</td><td>无分散化，回撤大</td></tr>
    </tbody>
  </table>
  </div>
</div>

</div>

<script>
// 净值曲线
var chart1 = echarts.init(document.getElementById('chart-nav'));
var navData = {json.dumps(nav_json, ensure_ascii=False)};
var methodLabelMap = {json.dumps(method_names, ensure_ascii=False)};

var series = [];
var colors = ['#ef4444', '#3b82f6', '#10b981', '#f59e0b', '#8b5cf6', '#6b7280', '#ec4899', '#06b6d4'];
var idx = 0;
for (var method in navData) {{
  if (navData.hasOwnProperty(method)) {{
    series.push({{
      name: methodLabelMap[method] || method,
      type: 'line',
      data: navData[method].values,
      smooth: false,
      lineStyle: {{ width: 2 }},
      itemStyle: {{ color: colors[idx % colors.length] }},
      symbol: 'none',
    }});
    idx++;
  }}
}}

chart1.setOption({{
  tooltip: {{ trigger: 'axis' }},
  legend: {{ data: series.map(function(s) {{ return s.name; }}), top: 0 }},
  grid: {{ left: 50, right: 20, top: 40, bottom: 30 }},
  xAxis: {{
    type: 'category',
    data: navData[Object.keys(navData)[0]].dates,
    axisLabel: {{ rotate: 30, fontSize: 10 }},
  }},
  yAxis: {{
    type: 'value',
    name: '净值',
    scale: true,
  }},
  series: series,
}});

window.addEventListener('resize', function() {{
  chart1.resize();
}});
</script>

</body>
</html>
"""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)

    return output_path


def main():
    parser = argparse.ArgumentParser(description="生成多因子组合研究报告")
    parser.add_argument("--perf", type=str, default=None, help="绩效 CSV 路径")
    parser.add_argument("--weights", type=str, default=None, help="权重 CSV 路径")
    parser.add_argument("--nav", type=str, default=None, help="净值 CSV 路径")
    parser.add_argument("--output", type=str, default=None, help="输出 HTML 路径")
    args = parser.parse_args()

    perf_path = args.perf or os.path.join(REPORT_DIR, "multi_factor_performance.csv")
    weights_path = args.weights or os.path.join(REPORT_DIR, "multi_factor_weights.csv")
    nav_path = args.nav or os.path.join(REPORT_DIR, "multi_factor_nav.csv")
    output_path = args.output or os.path.join(REPORT_DIR, "multi_factor_report.html")

    print(f"\n  生成多因子组合研究报告")
    print(f"  {'─'*50}")
    print(f"  绩效: {perf_path}")
    print(f"  权重: {weights_path}")
    print(f"  净值: {nav_path}")

    path = generate_multi_factor_report(perf_path, weights_path, nav_path, output_path)
    print(f"\n  ✅ 报告生成: {path}")


if __name__ == "__main__":
    main()
