#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
方向 A4: 全因子总览报告生成器
================================
从 factor_ranking.csv + factor_corr_matrix.csv + factor_clusters.csv
生成全因子总览 HTML 报告。

报告内容:
  1. 总览仪表盘 (多少个S/A/B/C，平均得分)
  2. 因子排名表 (全量，可搜索排序)
  3. 分类分析 (各分类平均得分、最佳因子)
  4. 相关性热力图 (ECharts heatmap)
  5. 聚类分析 (每簇代表因子 + 簇内成员)
  6. 独立因子池 (推荐使用的因子列表)

用法:
  python3 scripts/generate_overview_report.py
"""

import os
import sys
import argparse
import json

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from factor_lib.registry import FACTOR_REGISTRY

import numpy as np
import pandas as pd

def generate_overview_report(ranking_df, corr_matrix, cluster_df, indep_df, output_path):
    """生成全因子总览 HTML 报告"""

    total_factors = len(ranking_df)
    grade_counts = ranking_df["grade"].value_counts().reindex(
        ["S", "A+", "A", "B+", "B", "C+", "C", "D"], fill_value=0
    )
    avg_score = ranking_df["total_score"].mean()
    s_count = int(grade_counts.get("S", 0))
    a_count = int(grade_counts.get("A+", 0)) + int(grade_counts.get("A", 0))
    b_count = int(grade_counts.get("B+", 0)) + int(grade_counts.get("B", 0))
    c_count = int(grade_counts.get("C+", 0)) + int(grade_counts.get("C", 0))
    d_count = int(grade_counts.get("D", 0))

    # 分类统计
    cat_stats = ranking_df.groupby("category").agg(
        n_factors=("factor", "count"),
        avg_score=("total_score", "mean"),
        avg_icir=("icir", lambda x: abs(x).mean()),
    ).sort_values("avg_score", ascending=False)

    # 星级分布数据
    stars_data = []
    for grade in ["S", "A+", "A", "B+", "B", "C+", "C", "D"]:
        count = int(grade_counts.get(grade, 0))
        if count > 0:
            stars_data.append({"grade": grade, "count": count})

    # 排名表数据
    ranking_table = []
    for _, r in ranking_df.iterrows():
        star_str = "★" * int(r["stars"]) + "☆" * (7 - int(r["stars"]))
        ranking_table.append({
            "rank": int(r["rank"]),
            "factor": r["factor"],
            "category": r["category"],
            "stars": star_str,
            "grade": r["grade"],
            "score": round(float(r["total_score"]), 2),
            "icir": round(float(r["icir"]), 4) if pd.notna(r["icir"]) else None,
            "monotonicity": round(float(r["monotonicity_score"]), 3) if pd.notna(r["monotonicity_score"]) else None,
            "perm_p": round(float(r["perm_p_value"]), 4) if pd.notna(r["perm_p_value"]) else None,
            "sharpe": round(float(r["sharpe"]), 3) if pd.notna(r["sharpe"]) else None,
            "annual_return": round(float(r["annual_return"]), 4) if pd.notna(r["annual_return"]) else None,
            "max_dd": round(float(r["max_drawdown"]), 4) if pd.notna(r["max_drawdown"]) else None,
        })

    # 相关性热力图数据 (取 top 30 因子避免图太大)
    top_factors = ranking_df.head(30)["factor"].tolist()
    top_factors = [f for f in top_factors if f in corr_matrix.index]
    corr_top = corr_matrix.loc[top_factors, top_factors]

    # 热力图数据格式: [row_idx, col_idx, value]
    heatmap_data = []
    for i, row_f in enumerate(top_factors):
        for j, col_f in enumerate(top_factors):
            val = corr_top.iloc[i, j]
            if i != j:  # 跳过对角线
                heatmap_data.append([i, j, round(float(val), 3)])

    # 聚类数据
    clusters_info = []
    for c in sorted(cluster_df["cluster"].unique()):
        factors = cluster_df[cluster_df["cluster"] == c]["factor"].tolist()
        rep_row = indep_df[indep_df["cluster"] == c]
        rep = rep_row.iloc[0]["representative"] if len(rep_row) > 0 else factors[0]
        rep_grade = ""
        rep_score = ""
        if rep in ranking_df["factor"].values:
            r = ranking_df[ranking_df["factor"] == rep].iloc[0]
            rep_grade = r["grade"]
            rep_score = round(float(r["total_score"]), 2)
        clusters_info.append({
            "cluster": int(c),
            "n_factors": len(factors),
            "representative": rep,
            "rep_grade": rep_grade,
            "rep_score": rep_score,
            "factors": factors,
        })

    # JSON 数据（供 ECharts 使用）
    stars_data_json = json.dumps(stars_data, ensure_ascii=False)
    top_factors_json = json.dumps(top_factors, ensure_ascii=False)
    heatmap_data_json = json.dumps(heatmap_data, ensure_ascii=False)
    cat_stats_json = cat_stats.reset_index().to_json(orient="records", force_ascii=False)

    # 生成 HTML
    html = f"""<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>因子有效性总览报告</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{
  font-family: -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif;
  background: #f8f9fa; color: #1a1a2e; line-height: 1.6; font-size: 14px;
}}
.container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}

.hero {{
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
  color: #fff; padding: 40px; border-radius: 16px; margin-bottom: 24px;
}}
.hero h1 {{ font-size: 28px; margin-bottom: 8px; }}
.hero .subtitle {{ font-size: 14px; opacity: 0.8; }}
.hero .stats {{ display:flex; gap:24px; margin-top:20px; flex-wrap:wrap; }}
.hero .stat {{ text-align:center; }}
.hero .stat .value {{ font-size: 28px; font-weight: 700; }}
.hero .stat .label {{ font-size: 12px; opacity: 0.7; }}

.cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 24px; }}
.card {{
  background: #fff; border-radius: 12px; padding: 20px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}}
.card .value {{ font-size: 28px; font-weight: 700; color: #3b82f6; }}
.card .label {{ font-size: 12px; color: #6b7280; margin-top: 4px; }}

.section {{
  background: #fff; border-radius: 12px; padding: 24px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 24px;
}}
.section h2 {{
  font-size: 18px; margin-bottom: 16px; padding-bottom: 10px;
  border-bottom: 2px solid #3b82f6;
}}
.section h3 {{ font-size: 15px; margin: 20px 0 10px; color: #3b82f6; }}

table {{ width:100%; border-collapse:collapse; font-size:13px; }}
th {{
  background: #f8f9fa; padding: 10px 8px; text-align:left;
  font-weight: 600; border-bottom: 2px solid #e5e7eb; cursor: pointer;
  position: sticky; top: 0; z-index: 10;
}}
td {{ padding: 8px; border-bottom: 1px solid #e5e7eb; }}
tr:hover {{ background: #f8f9fa; }}
.table-wrap {{ overflow-x: auto; max-height: 600px; overflow-y: auto; }}

.stars {{ color: #f59e0b; letter-spacing: 2px; font-size: 12px; }}
.grade-S {{ color: #ef4444; font-weight: 700; }}
.grade-A {{ color: #f59e0b; font-weight: 600; }}
.grade-B {{ color: #3b82f6; font-weight: 500; }}
.grade-C {{ color: #6b7280; }}
.grade-D {{ color: #9ca3af; }}

.chart {{ width: 100%; min-height: 400px; }}

.cluster-grid {{
  display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px;
}}
.cluster-card {{
  background: #f8f9fa; border-radius: 8px; padding: 16px;
  border-left: 4px solid #3b82f6;
}}
.cluster-card h4 {{ margin-bottom: 8px; }}
.cluster-card .rep {{
  font-size: 14px; font-weight: 600; color: #3b82f6; margin-bottom: 8px;
}}
.cluster-card ul {{ list-style: none; padding: 0; }}
.cluster-card li {{
  font-size: 12px; padding: 3px 0; color: #4b5563;
  border-bottom: 1px dashed #e5e7eb;
}}
.cluster-card li:last-child {{ border-bottom: none; }}

.cat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; }}
.cat-item {{
  background: #f8f9fa; border-radius: 8px; padding: 12px;
}}
.cat-item .cat-name {{ font-weight: 600; font-size: 13px; margin-bottom: 4px; }}
.cat-item .cat-meta {{ font-size: 11px; color: #6b7280; }}

@media (max-width: 768px) {{
  .container {{ padding: 12px; }}
  .hero {{ padding: 24px; }}
  .hero h1 {{ font-size: 22px; }}
  .cards {{ grid-template-columns: repeat(2, 1fr); }}
}}
</style>
</head>
<body>
<div class="container">

<div class="hero">
  <h1>因子有效性总览报告</h1>
  <div class="subtitle">全因子筛选 · 7 维评级 · 聚类分析 · 独立因子池</div>
  <div class="stats">
    <div class="stat"><div class="value">{total_factors}</div><div class="label">总因子数</div></div>
    <div class="stat"><div class="value" style="color:#ef4444">{s_count}</div><div class="label">S 级</div></div>
    <div class="stat"><div class="value" style="color:#f59e0b">{a_count}</div><div class="label">A 级</div></div>
    <div class="stat"><div class="value" style="color:#3b82f6">{b_count}</div><div class="label">B 级</div></div>
    <div class="stat"><div class="value">{avg_score:.2f}</div><div class="label">平均得分</div></div>
  </div>
</div>

<div class="cards">
  <div class="card"><div class="value">{len(indep_df)}</div><div class="label">独立因子簇</div></div>
  <div class="card"><div class="value">{int(grade_counts.sum())}</div><div class="label">有效因子</div></div>
  <div class="card"><div class="value">{len(cat_stats)}</div><div class="label">因子分类</div></div>
  <div class="card"><div class="value">7</div><div class="label">评级维度</div></div>
</div>

<!-- 评级分布 -->
<div class="section">
  <h2>1. 评级分布</h2>
  <div id="chart-grade-dist" class="chart" style="min-height:300px"></div>
</div>

<!-- 因子排名表 -->
<div class="section">
  <h2>2. 因子排名</h2>
  <p style="color:#6b7280;font-size:12px;margin-bottom:12px">点击表头排序。评级：S (黄金) / A+ (强有效) / A (有效) / B+ (弱有效) / B (边际) / C+ / C (弱信号) / D (无效)</p>
  <div class="table-wrap">
  <table id="ranking-table">
    <thead>
      <tr>
        <th onclick="sortTable(0)">排名</th>
        <th onclick="sortTable(1)">因子</th>
        <th onclick="sortTable(2)">分类</th>
        <th>星级</th>
        <th onclick="sortTable(4)">等级</th>
        <th onclick="sortTable(5)">得分</th>
        <th onclick="sortTable(6)">|ICIR|</th>
        <th onclick="sortTable(7)">单调性</th>
        <th onclick="sortTable(8)">置换p</th>
        <th onclick="sortTable(9)">夏普</th>
        <th onclick="sortTable(10)">年化</th>
        <th onclick="sortTable(11)">回撤</th>
      </tr>
    </thead>
    <tbody>
"""

    # 表格行
    for r in ranking_table:
        grade_class = f"grade-{r['grade'].replace('+', '')}"
        icir_val = f"{abs(r['icir']):.4f}" if r["icir"] is not None else "N/A"
        mono_val = f"{abs(r['monotonicity']):.3f}" if r["monotonicity"] is not None else "N/A"
        perm_val = f"{r['perm_p']:.4f}" if r["perm_p"] is not None else "N/A"
        sharpe_val = f"{r['sharpe']:+.3f}" if r["sharpe"] is not None else "N/A"
        ann_val = f"{r['annual_return']:+.2%}" if r["annual_return"] is not None else "N/A"
        dd_val = f"{r['max_dd']:.2%}" if r["max_dd"] is not None else "N/A"
        html += f"""      <tr>
        <td>{r['rank']}</td>
        <td><strong>{r['factor']}</strong></td>
        <td>{r['category']}</td>
        <td><span class="stars">{r['stars']}</span></td>
        <td class="{grade_class}">{r['grade']}</td>
        <td>{r['score']:.2f}</td>
        <td>{icir_val}</td>
        <td>{mono_val}</td>
        <td>{perm_val}</td>
        <td>{sharpe_val}</td>
        <td>{ann_val}</td>
        <td>{dd_val}</td>
      </tr>
"""

    html += f"""    </tbody>
  </table>
  </div>
</div>

<!-- 分类分析 -->
<div class="section">
  <h2>3. 分类分析</h2>
  <div id="chart-category" class="chart" style="min-height:350px"></div>
  <div class="cat-grid" style="margin-top:20px">
"""

    for cat, row in cat_stats.iterrows():
        best_in_cat = ranking_df[ranking_df["category"] == cat].iloc[0]
        html += f"""    <div class="cat-item">
      <div class="cat-name">{cat}</div>
      <div class="cat-meta">{int(row['n_factors'])} 因子 · 均分 {row['avg_score']:.2f} · 平均 |ICIR| {row['avg_icir']:.3f}</div>
      <div class="cat-meta" style="color:#3b82f6">最佳: {best_in_cat['factor']} ({best_in_cat['grade']})</div>
    </div>
"""

    html += f"""  </div>
</div>

<!-- 相关性热力图 -->
<div class="section">
  <h2>4. 因子相关性热力图</h2>
  <p style="color:#6b7280;font-size:12px;margin-bottom:12px">Top 30 因子（按得分排名）的 Spearman 相关系数。红色=正相关，蓝色=负相关，颜色越深相关性越强。</p>
  <div id="chart-corr-heatmap" class="chart" style="min-height:500px"></div>
</div>

<!-- 聚类分析 -->
<div class="section">
  <h2>5. 聚类分析</h2>
  <p style="color:#6b7280;font-size:12px;margin-bottom:16px">基于因子间相关性的层次聚类（Ward 方法）。每簇内因子高度相关，选代表因子即可。</p>
  <div class="cluster-grid">
"""

    for cl in clusters_info:
        html += f"""    <div class="cluster-card">
      <h4>簇 {cl['cluster']} · {cl['n_factors']} 因子</h4>
      <div class="rep">代表因子: {cl['representative']} <span style="font-weight:normal;color:#6b7280">[{cl['rep_grade']} {cl['rep_score']}分]</span></div>
      <ul>
"""
        for f in cl["factors"]:
            meta = FACTOR_REGISTRY.get(f)
            cat = meta.category if meta else "?"
            gr = ""
            if f in ranking_df["factor"].values:
                r = ranking_df[ranking_df["factor"] == f].iloc[0]
                gr = r["grade"]
            html += f"        <li>• {f} <span style=\"color:#9ca3af\">({cat}) [{gr}]</span></li>\n"
        html += "      </ul>\n    </div>\n"

    html += f"""  </div>
</div>

<!-- 独立因子池 -->
<div class="section">
  <h2>6. 独立因子池</h2>
  <p style="color:#6b7280;font-size:12px;margin-bottom:16px">从每个簇中选出的代表性因子，构成低冗余、高独立的因子池，适合构建多因子组合。</p>
  <div class="table-wrap">
  <table>
    <thead>
      <tr><th>簇</th><th>代表因子</th><th>分类</th><th>等级</th><th>得分</th><th>|ICIR|</th><th>夏普</th><th>年化</th><th>簇内因子数</th></tr>
    </thead>
    <tbody>
"""

    for _, r in indep_df.iterrows():
        factor = r["representative"]
        if factor in ranking_df["factor"].values:
            rf = ranking_df[ranking_df["factor"] == factor].iloc[0]
            grade = rf["grade"]
            score = f"{rf['total_score']:.2f}"
            icir = f"{abs(rf['icir']):.4f}"
            sharpe = f"{rf['sharpe']:+.3f}"
            ann = f"{rf['annual_return']:+.2%}"
            cat = rf["category"]
        else:
            grade = "-"
            score = "-"
            icir = "-"
            sharpe = "-"
            ann = "-"
            meta = FACTOR_REGISTRY.get(factor)
            cat = meta.category if meta else "?"
        html += f"""      <tr>
        <td>{int(r['cluster'])}</td>
        <td><strong>{factor}</strong></td>
        <td>{cat}</td>
        <td class="grade-{grade.replace('+', '')}">{grade}</td>
        <td>{score}</td>
        <td>{icir}</td>
        <td>{sharpe}</td>
        <td>{ann}</td>
        <td>{int(r['n_factors'])}</td>
      </tr>
"""

    html += f"""    </tbody>
  </table>
  </div>
</div>

</div>

<script>
// 评级分布
var chart1 = echarts.init(document.getElementById('chart-grade-dist'));
var gradeData = {stars_data_json};
chart1.setOption({{
  tooltip: {{ trigger: 'axis' }},
  grid: {{ left: 40, right: 20, top: 30, bottom: 30 }},
  xAxis: {{ type: 'category', data: gradeData.map(d => d.grade) }},
  yAxis: {{ type: 'value', name: '因子数' }},
  series: [{{
    type: 'bar',
    data: gradeData.map(d => d.count),
    itemStyle: {{
      color: function(params) {{
        var colors = ['#ef4444', '#f59e0b', '#eab308', '#84cc16', '#22c55e', '#3b82f6', '#8b5cf6', '#6b7280'];
        return colors[params.dataIndex] || '#6b7280';
      }}
    }},
    label: {{ show: true, position: 'top' }}
  }}]
}});

// 分类分析
var chart2 = echarts.init(document.getElementById('chart-category'));
var catData = {cat_stats_json};
chart2.setOption({{
  tooltip: {{ trigger: 'axis', axisPointer: {{ type: 'shadow' }} }},
  legend: {{ data: ['平均得分', '平均|ICIR|'], right: 10 }},
  grid: {{ left: 40, right: 40, top: 40, bottom: 60 }},
  xAxis: {{ type: 'category', data: catData.map(d => d.category), axisLabel: {{ rotate: 30, fontSize: 11 }} }},
  yAxis: [
    {{ type: 'value', name: '平均得分', min: 0, max: 7 }},
    {{ type: 'value', name: '平均|ICIR|' }}
  ],
  series: [
    {{ name: '平均得分', type: 'bar', data: catData.map(d => d.avg_score.toFixed(2)), itemStyle: {{ color: '#3b82f6' }} }},
    {{ name: '平均|ICIR|', type: 'line', yAxisIndex: 1, data: catData.map(d => +d.avg_icir.toFixed(3)), itemStyle: {{ color: '#ef4444' }}, smooth: true }}
  ]
}});

// 相关性热力图
var chart3 = echarts.init(document.getElementById('chart-corr-heatmap'));
var topFactors = {top_factors_json};
var heatData = {heatmap_data_json};
chart3.setOption({{
  tooltip: {{
    position: 'top',
    formatter: function(p) {{
      return topFactors[p.data[0]] + ' ↔ ' + topFactors[p.data[1]] + '<br/>corr: ' + p.data[2];
    }}
  }},
  grid: {{ left: 120, right: 20, top: 20, bottom: 120 }},
  xAxis: {{
    type: 'category', data: topFactors,
    axisLabel: {{ rotate: 45, fontSize: 10 }},
    splitArea: {{ show: true }}
  }},
  yAxis: {{
    type: 'category', data: topFactors,
    axisLabel: {{ fontSize: 10 }},
    splitArea: {{ show: true }}
  }},
  visualMap: {{
    min: -1, max: 1, calculable: true,
    orient: 'horizontal', left: 'center', bottom: 0,
    inRange: {{ color: ['#3b82f6', '#ffffff', '#ef4444'] }}
  }},
  series: [{{
    type: 'heatmap',
    data: heatData,
    label: {{ show: false }},
    emphasis: {{ itemStyle: {{ shadowBlur: 10, shadowColor: 'rgba(0,0,0,0.3)' }} }}
  }}]
}});

// 表格排序
var sortDir = Array(12).fill(-1);
function sortTable(col) {{
  var table = document.getElementById('ranking-table');
  var tbody = table.querySelector('tbody');
  var rows = Array.from(tbody.querySelectorAll('tr'));
  sortDir[col] *= -1;
  rows.sort(function(a, b) {{
    var aVal = a.children[col].textContent.trim();
    var bVal = b.children[col].textContent.trim();
    var aNum = parseFloat(aVal);
    var bNum = parseFloat(bVal);
    if (!isNaN(aNum) && !isNaN(bNum)) {{
      return (aNum - bNum) * sortDir[col];
    }}
    return aVal.localeCompare(bVal) * sortDir[col];
  }});
  rows.forEach(function(r) {{ tbody.appendChild(r); }});
}}

// 响应式
window.addEventListener('resize', function() {{
  chart1.resize(); chart2.resize(); chart3.resize();
}});
</script>

</body>
</html>
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    return output_path

def main():
    parser = argparse.ArgumentParser(description="生成全因子总览报告")
    parser.add_argument("--ranking", type=str, default=None, help="评级 CSV 路径")
    parser.add_argument("--corr", type=str, default=None, help="相关矩阵 CSV 路径")
    parser.add_argument("--clusters", type=str, default=None, help="聚类 CSV 路径")
    parser.add_argument("--indep", type=str, default=None, help="独立因子 CSV 路径")
    parser.add_argument("--output", type=str, default=None, help="输出 HTML 路径")
    parser.add_argument("--n-clusters", type=int, default=5, help="聚类数量")
    args = parser.parse_args()

    report_dir = os.path.join(PROJECT_ROOT, "factor_test_reports")

    ranking_path = args.ranking or os.path.join(report_dir, "factor_ranking.csv")
    corr_path = args.corr or os.path.join(report_dir, "factor_corr_matrix.csv")
    clusters_path = args.clusters or os.path.join(report_dir, "factor_clusters.csv")
    indep_path = args.indep or os.path.join(report_dir, "independent_factors.csv")
    output_path = args.output or os.path.join(report_dir, "factor_overview_report.html")

    print(f"\n  生成全因子总览报告")
    print(f"  {'─' * 50}")

    # 检查文件
    for p, name in [(ranking_path, "评级"), (corr_path, "相关矩阵"), (clusters_path, "聚类")]:
        if not os.path.exists(p):
            print(f"❌ 缺少 {name} 数据: {p}")
            sys.exit(1)

    ranking_df = pd.read_csv(ranking_path)
    corr_matrix = pd.read_csv(corr_path, index_col=0)
    cluster_df = pd.read_csv(clusters_path)

    if os.path.exists(indep_path):
        indep_df = pd.read_csv(indep_path)
    else:
        print(f"  ⚠️  独立因子文件不存在，从聚类生成")
        indep_df = None  # 将在相关性脚本中生成

    path = generate_overview_report(ranking_df, corr_matrix, cluster_df, indep_df, output_path)
    print(f"\n  ✅ 报告生成: {path}")
    print(f"     因子数: {len(ranking_df)}")
    print(f"     聚类数: {args.n_clusters}")

if __name__ == "__main__":
    main()
